defaults:
  - base.yaml
  - _self_

loss: "dino"
return_two_views: False
num_epochs: 500
weight_decay: 0
lr: 5e-4
warmup_epochs: 50

crops:
  global_crops_scale: [0.15, 1.0]
  local_crops_number: 8
  local_crops_scale: [0.05, 0.15]
  local_crops_size: [96, 96]

ibot_mask_ratio_min_max: [0.1, 0.5]
mask_probability: 0.5
head_n_prototypes: 65536
head_bottleneck_dim: 256
head_nlayers: 3
head_hidden_dim: 2048
patch_size: 16
teacher_temp: 0.07
warmup_teacher_temp: 0.04
wd_start: 0.04
wd_end: 0.4
use_lr_scheduler: True
koleo_loss_weight: 0.2
ibot_loss_weight: 2