channels:
  - pytorch
  - nvidia
  - default
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip
  - pip:
    - lightning>=2.2.0
    - pandas
    - numpy
    - scikit-learn
    - hydra-core
    - wandb
    - jupyter
    - flake8
    - black
    - matplotlib
    - seaborn
    - pytest
    - pyro_ppl==1.8.4
    - Send2Trash==1.8.2
    - imageio==2.26.0
    - opencv-python
    - tensorboard
    - scikit-image